/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeonquest;

import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hamba Allah
 */
public class Fight extends javax.swing.JFrame {

    /**
     * Creates new form Fight
     */
    Main m = new Main();
    Kota k = new Kota();
    LinkedList lk = new LinkedList();

    public static int idM;
    int eHP;
    int pATK;
    int pDEF;
    int mATK;
    int mDEF;
    int mDMG;
    int pDMG;
    int loot;
    int hit;
    int serang = 1;

    public Fight() {
        initComponents();
        getMonster();
        //idM=m.var[2];
        //this.eHP = m.monster[idM][0];
        setBgIMG();
        setMonster();
        this.setLocationRelativeTo(null);
    }

    public void getMonster() {
        lk.push(new LinkedListNode(m.monster[m.var[2]][0], m.var[2]));
        this.idM = lk.head.idx;
        this.eHP = lk.head.HP;
        System.out.println(lk.head.idx);
    }

    public void delAllMonster() {
        while (lk.head != null) {
            lk.qpop();
        }
        lk.qpop();
    }

    public void setMonster() {
        System.out.println(idM);
        System.out.println(m.monsterName[idM]);
        this.pATK = m.player[3] + m.weapon[m.player[5]][0];
        this.pDEF = m.player[4] + m.armor[m.player[6]][1];
        this.mATK = m.monster[idM][1];
        this.mDEF = m.monster[idM][2];
        this.mDMG = mATK - pDEF;
        this.pDMG = pATK - mDEF;
        jProgressBar1.setToolTipText("HP = " + m.player[1]);
        jProgressBar2.setToolTipText("HP = " + eHP);
        jProgressBar1.setMaximum(m.health[m.player[0] - 1]);
        jProgressBar2.setMaximum(m.monster[idM][0]);

        jProgressBar1.setValue(m.player[1]);
        jProgressBar2.setValue(eHP);
        if (serang == 0) {
            jButton2.setEnabled(false);
        } else {
            jButton2.setEnabled(true);
        }
    }

    public void setBgIMG() {
        jLabel4.setText(m.monsterName[m.var[2]]);
        if (idM == 0) {
            jLabel5.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Slime.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT)));
            jLabel2.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Floor\\Floor1.jpg").getImage().getScaledInstance(718, 350, Image.SCALE_DEFAULT)));
        } else if (idM == 1) {
            jLabel5.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Orc.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT)));
            jLabel2.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Floor\\Floor2.jpg").getImage().getScaledInstance(718, 350, Image.SCALE_DEFAULT)));
        } else if (idM == 2) {
            jLabel5.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Werewolf.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT)));
            jLabel2.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Floor\\Floor3.png").getImage().getScaledInstance(718, 350, Image.SCALE_DEFAULT)));
        } else if (idM == 3) {
            jLabel5.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Snake.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT)));
            jLabel2.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Floor\\Floor4.jpg").getImage().getScaledInstance(718, 350, Image.SCALE_DEFAULT)));
        } else if (idM == 4) {
            jLabel5.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Minotaur.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT)));
            jLabel2.setIcon(new ImageIcon(new ImageIcon("E:\\asset\\Floor\\Floor5.png").getImage().getScaledInstance(718, 350, Image.SCALE_DEFAULT)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(718, 392));
        setMinimumSize(new java.awt.Dimension(718, 392));
        getContentPane().setLayout(null);

        jProgressBar1.setToolTipText("");
        jProgressBar1.setValue(90);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 50, 146, 14);

        jProgressBar2.setValue(90);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(546, 50, 146, 14);

        jButton1.setText("Kembali");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 310, 120, 23);

        jButton2.setText("Serang");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 310, 120, 23);

        jLabel3.setText("Player");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 30, 60, 14);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(546, 30, 100, 14);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 140, 127, 106);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(2, 75, 700, 209);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        serang = 1;
        k.fgt = 0;
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double chance = 1;
        ImageIcon icon = new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Slime.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT));
        if (idM == 0) {
            chance = 0.90;
            icon = new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Slime.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT));
        } else if (idM == 1) {
            chance = 0.80;
            icon = new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Orc.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT));
        } else if (idM == 2) {
            chance = 0.70;
            icon = new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Werewolf.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT));
        } else if (idM == 3) {
            chance = 0.60;
            icon = new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Snake.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT));
        } else if (idM == 4) {
            chance = 0.50;
            icon = new ImageIcon(new ImageIcon("E:\\asset\\Monster\\Minotaur.png").getImage().getScaledInstance(127, 106, Image.SCALE_DEFAULT));
        }

        if (new Random().nextDouble() <= chance) {
            if (pDMG >= 0) {
                eHP -= pDMG;
            } else {
                eHP -= 0;
                pDMG = 0;
            }

            JOptionPane.showMessageDialog(null,
                    new JLabel("Attack Berhasil \n" + "DMG: " + pDMG, icon, JLabel.CENTER),
                    "Berhasil",
                    JOptionPane.PLAIN_MESSAGE);
        } else {
            if (mDMG >= 0) {
                m.player[1] -= mDMG;
            } else {
                m.player[1] -= 0;
                mDMG = 0;
            }
            JOptionPane.showMessageDialog(null, new JLabel("Attack Gagal \n" + "Terkena: " + mDMG, icon, JLabel.CENTER), "Gagal", JOptionPane.PLAIN_MESSAGE);
        }

        if (eHP <= 0) {
            m.player[2] += m.monster[idM][3];
            m.levelUP();
            JOptionPane.showMessageDialog(null, "Monster Berhasil Dibunuh", "Selamat", JOptionPane.INFORMATION_MESSAGE);
            lk.qpop();
            serang = 0;
            if (idM <= 2) {
                loot = (int) (Math.random() * 2) + 1;
                m.iInventory[idM + 1] += loot;
            } else if (idM == 4) {
                if (m.var[3] == 0) {
                    m.var[3] = 1;
                    k.fgt = 0;
                    m.newGame = 0;
                    m.endGame = 1;
                    dialogFrm d = new dialogFrm();
                    d.setVisible(true);
                    this.dispose();
                }
            } else {
                m.player[7] += 60;
            }
            if (m.var[2] < 4) {
                if (m.var[2] == m.var[1]) {
                    m.var[1] += 1;
                }
            }
            System.out.println(lk.head);
        } else if (m.player[1] <= 0) {
            m.player[1] = 1;
            JOptionPane.showMessageDialog(null, "Kamu Kalah T_T", "Oh No!!", JOptionPane.INFORMATION_MESSAGE);
        }
        setMonster();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
